name: ${pluginName}
version: ${version}
main: ${group}.${packageName}.plugin.${pluginName}Plugin
api-version: ${paperVersion}
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}
  - org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}